import React, { useState, useEffect } from 'react';
import { useAuth } from '../AuthContext';
import { useNavigate } from 'react-router-dom';

function Kundli() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [isGenerating, setIsGenerating] = useState(false);
  const [kundliData, setKundliData] = useState(null);

  useEffect(() => {
    if (!user) {
      navigate('/auth');
      return;
    }
  }, [user, navigate]);

  const generateKundli = async () => {
    setIsGenerating(true);
    
    // Simulate API call - replace with actual chatbot integration
    setTimeout(() => {
      setKundliData({
        name: user?.full_name || 'User',
        birthDate: user?.birth_date || 'Not provided',
        birthTime: user?.birth_time || 'Not provided',
        birthPlace: user?.birth_place || 'Not provided',
        generated: true
      });
      setIsGenerating(false);
    }, 3000);
  };

  const chatWithBot = () => {
    navigate('/chat', { 
      state: { 
        initialMessage: `Generate my personalized Kundli based on my birth details: ${user?.full_name}, born on ${user?.birth_date} at ${user?.birth_time} in ${user?.birth_place}. Please provide detailed astrological analysis.` 
      }
    });
  };

  return (
    <div className="kundli-container">
      <div className="kundli-header">
        <h1 className="page-title">🔮 Your Personal Kundli</h1>
        <p className="page-subtitle">Discover your cosmic blueprint</p>
      </div>

      <div className="user-info-card">
        <h3>📋 Your Birth Details</h3>
        <div className="birth-details">
          <div className="detail-item">
            <span className="detail-label">Name:</span>
            <span className="detail-value">{user?.full_name || 'Not provided'}</span>
          </div>
          <div className="detail-item">
            <span className="detail-label">Birth Date:</span>
            <span className="detail-value">{user?.birth_date || 'Not provided'}</span>
          </div>
          <div className="detail-item">
            <span className="detail-label">Birth Time:</span>
            <span className="detail-value">{user?.birth_time || 'Not provided'}</span>
          </div>
          <div className="detail-item">
            <span className="detail-label">Birth Place:</span>
            <span className="detail-value">{user?.birth_place || 'Not provided'}</span>
          </div>
        </div>
      </div>

      {!kundliData ? (
        <div className="generate-section">
          <div className="generate-card">
            <div className="generate-icon">🌟</div>
            <h2>Generate Your Kundli</h2>
            <p>Get personalized astrological insights based on your birth details</p>
            
            <div className="generate-buttons">
              <button 
                className="generate-btn primary"
                onClick={generateKundli}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <span className="loading-spinner">🔄</span>
                    Generating Kundli...
                  </>
                ) : (
                  <>
                    <span>🔮</span>
                    Generate Kundli
                  </>
                )}
              </button>

              <button 
                className="generate-btn secondary"
                onClick={chatWithBot}
              >
                <span>💬</span>
                Chat for Detailed Analysis
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="kundli-result">
          <div className="result-header">
            <h2>✨ Your Kundli is Ready!</h2>
            <p>Based on your birth details</p>
          </div>
          
          <div className="kundli-charts">
            <div className="chart-placeholder">
              <div className="chart-title">Birth Chart</div>
              <div className="chart-content">🔯</div>
              <p>Detailed chart will be generated by chatbot</p>
            </div>
          </div>

          <div className="action-buttons">
            <button className="action-btn primary" onClick={chatWithBot}>
              💬 Get Detailed Reading
            </button>
            <button className="action-btn secondary" onClick={() => setKundliData(null)}>
              🔄 Generate New
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default Kundli;
